default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manyou_task_development
test:
  <<: *default
  database: manyou_task_test
  
production:
  <<: *default
  database: manyou_task_production
  username: manyou_task
  password: <%= ENV['MANYOU_TASK_DATABASE_PASSWORD'] %>
